<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container-fluid">

 <div class="row">
 
 <div class="col-sm-4" style="background-color:black; color:#ffffff;">
      <img src="http://hyperphysics.phy-astr.gsu.edu/hbase/thermo/imgheat/diescyl.gif" alt="Smiley face" height="500px" width="270px"> 
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.<br>
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.<br/>
       <iframe src="https://ninjaweb.xyz" height="250px" width="270px"></iframe> 
    </div>
    <div class="col-sm-8" style="background-color:black; color:#ffffff;">
      Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.
      <img src="http://www.success.com/sites/default/files/15_1.jpg" alt="Smiley face" height="200px" width="270px"> 
      <br/>
      <img src="https://www.brainyquote.com/photos_tr/en/m/mattcameron/333397/mattcameron1.jpg" alt="Smiley face" height="200px" width="270px"> 
      <img src="http://quotesideas.com/wp-content/uploads/2015/07/The-Reason-I-Am-Fat-Very-Funny-Cute-Quote-Life-Picture.jpg" alt="Smiley face" height="200px" width="270px"> 
      
    </div>
 
 <div/>

</div>

</body>
</html>
